# Generated by Django 3.2.5 on 2021-11-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
        ('posts', '0003_comment'),
    ]

    operations = [
    ]
